services:
  db:
    image: postgres:16
    container_name: planner
    environment:
      POSTGRES_DB: planner
      POSTGRES_USER: planner_user
      POSTGRES_PASSWORD: planner_pass
    ports:
      - "5432:5432"
    volumes:
      - planner_pgdata:/var/lib/postgresql/data

volumes:
  planner_pgdata: